services:
  - type: web
    name: discord-bot-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    healthCheckPath: "/"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
        
